# LEAST SQUARES

$$
\begin{aligned}
AX &= B \Rightarrow X\beta = y \\
(X^T X)^{-1} X^T X\beta &= (X^T X)^{-1} X^T y \\
\beta &= (X^T X)^{-1} X^T y
\end{aligned}
$$


$$
\begin{aligned}
\beta &= (X^T X)^{-1} X^T y \Rightarrow y \in C(X) \\[0.5em]
\text{Otherwise:} \\[0.5em]
\beta &= (X^T X)^{-1} X^T y^{a} \\[0.5em]
\text{Then:} \quad
&\left\{
\begin{array}{l}
y^{a} \in C(X) \\
y = X\beta + \epsilon \Rightarrow (y+\epsilon) \in C(X)
\end{array}
\right.
\end{aligned}
$$


In [61]:
import numpy as np
from sympy import Matrix


In [71]:
m = 10
n = 3

#create data
X = np.random.randn(m,n) #design matrix
y = np.random.randn(m, 1) #outcome measures (data)

np.shape(y)

(10, 1)

In [73]:
print(f"Matrix X: \n {X}"), print(" ")
print(f"Matrix y: \n {y}"), print(" ")

Matrix X: 
 [[ 0.73442924 -0.62484215 -0.18717041]
 [-0.73145854 -0.74336685 -1.90981731]
 [-0.19414905 -0.36907752 -0.62081246]
 [-0.57395747  2.45211526  0.25757598]
 [-1.23794883  0.84549305 -0.23693095]
 [-0.88500498  0.12173219 -0.06936101]
 [ 0.01236298  0.84969526  0.01758185]
 [ 0.45776717  1.97554087 -0.55162254]
 [ 0.05549468 -0.96710617  0.29838295]
 [ 0.7280732  -0.15279942 -1.00439104]]
 
Matrix y: 
 [[-0.69694784]
 [-0.36671128]
 [-0.24048944]
 [-0.61287868]
 [-1.53310997]
 [-0.43941992]
 [-0.22981242]
 [-0.48676878]
 [-0.05725059]
 [ 0.01958627]]
 


(None, None)

In [75]:
#try directly applying RREF
Xy = Matrix (np.concatenate([X,y], axis = 1))
print(Xy.rref())

(Matrix([
[1, 0, 0, 0],
[0, 1, 0, 0],
[0, 0, 1, 0],
[0, 0, 0, 1],
[0, 0, 0, 0],
[0, 0, 0, 0],
[0, 0, 0, 0],
[0, 0, 0, 0],
[0, 0, 0, 0],
[0, 0, 0, 0]]), (0, 1, 2, 3))


In [83]:
#now reapply to the normal equations
XtX = X.T@X
Xty = X.T@y
normEQ = Matrix(np.concatenate([XtX, Xty], axis = 1))
print(XtX), print(" ")
print(Xty), print(" ")
print(normEQ)

[[ 4.50016391 -1.65540077  0.61986563]
 [-1.65540077 13.40517247  0.97870252]
 [ 0.61986563  0.97870252  5.59756592]]
 
[[ 2.22704802]
 [-3.16025945]
 [ 1.44367261]]
 
Matrix([[4.50016390670905, -1.65540077331739, 0.619865627376073, 2.22704802273300], [-1.65540077331739, 13.4051724667056, 0.978702524238679, -3.16025944732812], [0.619865627376073, 0.978702524238679, 5.59756591528227, 1.44367260713801]])


In [85]:
Xsol = normEQ.rref()
Xsol = Xsol[0]
beta = Xsol[:,-1]

print(np.array(Xsol)), print(" ")
print(beta), print(' ')

[[1 0 0 0.384217529318084]
 [0 1 0 -0.206663984697949]
 [0 0 1 0.251497160029511]]
 
Matrix([[0.384217529318084], [-0.206663984697949], [0.251497160029511]])
 


(None, None)

In [87]:
#compare to the left- inverse
beta2 = np.linalg.inv(XtX) @ Xty
print(beta2)

[[ 0.38421753]
 [-0.20666398]
 [ 0.25149716]]


In [89]:
# with python solver
beta3 = np.linalg.solve(XtX, Xty)
print(beta3)

[[ 0.38421753]
 [-0.20666398]
 [ 0.25149716]]
