# Matrix Multiplication

In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [8]:
## Rules for multiplication validity

m = 4
n = 3
k = 6

#make some matrices
A = np.random.randn(m,n)
B = np.random.randn(n,k)
C = np.random.randn(m,k)

#test whitch multiplications are valid.
#think of your answer first, then test

np.matmul(A,B) #(4,3)x(3x6) = (4x6)
#np.matmul(A,A) #don't
np.matmul(A.T, C) #(3x4)x(4x6) = (3x6)
np.matmul(np.matrix.transpose(B),B) #(6x3)x(3x6) = (6x6)

array([[ 1.0542921 , -0.25421699,  0.26050259, -1.14155278,  0.44726667,
         1.61129737],
       [-0.25421699,  1.74995029, -1.03756223, -0.41156276,  1.96793415,
        -1.02238573],
       [ 0.26050259, -1.03756223,  0.64113198,  0.33585872, -1.12521587,
         0.71256264],
       [-1.14155278, -0.41156276,  0.33585872,  4.99228764, -1.91756046,
        -2.29467342],
       [ 0.44726667,  1.96793415, -1.12521587, -1.91756046,  2.84118609,
         0.04123959],
       [ 1.61129737, -1.02238573,  0.71256264, -2.29467342,  0.04123959,
         2.8881983 ]])

## Challenge

In [24]:
# implement matrix multiplication via layers
m = 4
n = 3

#generate 2 matrices (A,B)
A = np.random.randn(m,n)
B = np.random.randn(n,m)
#build the product matrix layer-wise (for-loop)
C1 = np.zeros((m,m))
              
for i in range(n):
    C1 += np.outer(A[:,i], B[i,:])

print(C1)
#implement the matrix multiplication directly
C2 = np.matmul(A,B)

#compare the results

if np.allclose(C1, C2):
    print("\nAs matrizes C1 e C2 são iguais dentro de uma margem numérica.")
else:
    print("\nAs matrizes C1 e C2 são diferentes.")
    print("Diferença:")
    print(C1 - C2)

for i in range(C1.shape[0]):  # Itera sobre as linhas
    for j in range(C1.shape[1]):  # Itera sobre as colunas
        if C1[i, j] == C2[i, j]:
            print(f"Elementos iguais em posição ({i}, {j}): {C1[i, j]}")
        else:
            print(f"Elementos diferentes em posição ({i}, {j}): C1={C1[i, j]}, C2={C2[i, j]}")
    
#print(direct)


[[ 0.03455602 -2.18333597 -1.17172298 -0.21443794]
 [-0.36450753  0.1483093  -0.10953727  0.12297168]
 [-0.03568563  0.00508205  0.79425716 -0.35479318]
 [ 4.97241187  1.21059511  0.37863002 -0.07526871]]

As matrizes C1 e C2 são iguais dentro de uma margem numérica.
Elementos iguais em posição (0, 0): 0.03455601841881217
Elementos iguais em posição (0, 1): -2.183335967084571
Elementos iguais em posição (0, 2): -1.1717229819173132
Elementos iguais em posição (0, 3): -0.21443794281894873
Elementos iguais em posição (1, 0): -0.36450752953679305
Elementos iguais em posição (1, 1): 0.1483092954853294
Elementos iguais em posição (1, 2): -0.10953726548546439
Elementos iguais em posição (1, 3): 0.12297167554792345
Elementos iguais em posição (2, 0): -0.03568562788648241
Elementos iguais em posição (2, 1): 0.005082047586446203
Elementos iguais em posição (2, 2): 0.7942571595183601
Elementos iguais em posição (2, 3): -0.35479318445065927
Elementos iguais em posição (3, 0): 4.97241186747486
Elem

## Order Operation

$$ (LIVE)^T = E^TV^TI^TL^T$$

In [32]:
n = 2
L = np.random.randn(n,n)
I = np.random.randn(n,n)
V = np.random.randn(n,n)
E = np.random.randn(n,n)

#result of forward multiplication and then transpose
res1 = np.matrix.transpose( L @ I @ V @ E )
print(res1)
print(" ")
#result of flipped multiplication of transposed matrices
res2 = E.T @ V.T @ I.T @ L.T
print(res2) 

#test equality by subtracting (ignore possible computer rounding errors)
res1-res2

[[ 6.65710732  7.85574662]
 [-2.5035678  -2.77318793]]
 
[[ 6.65710732  7.85574662]
 [-2.5035678  -2.77318793]]


array([[8.8817842e-16, 8.8817842e-16],
       [4.4408921e-16, 4.4408921e-16]])

## Matrix Vector Multiplication

In [44]:
m = 4

#create matrices
N = np.random.randint(-10,11,(m,m))
print(N)
print(" ")
S = np.round(N.T*N /m**2) #scaled symmetric
print(S)
print(" ")

#and vector
w = np.array([-1, 0, 1, 2])
print(w)
print(" ")

#with symmetric matrix
print(f"1-{S@w}")
print(" ")
print(f"2-{S.T@w}")
print(" ")
print(f"3-{w@S}")
print(" ")
print(f"4-{w.T@S.T}")
print(" ")
print(f"5-{w.T@S}")
print(" ")

[[ 7 -2 -9  6]
 [ 2  2  3 10]
 [-9  6 -1  8]
 [-2 10  8  4]]
 
[[ 3. -0.  5. -1.]
 [-0.  0.  1.  6.]
 [ 5.  1.  0.  4.]
 [-1.  6.  4.  1.]]
 
[-1  0  1  2]
 
1-[ 0. 13.  3.  7.]
 
2-[ 0. 13.  3.  7.]
 
3-[ 0. 13.  3.  7.]
 
4-[ 0. 13.  3.  7.]
 
5-[ 0. 13.  3.  7.]
 
