# Matrix Rank

* Terminology: r or rank(A), non negative integer.
* Maximum possible ran is min(m,n)
* Rank is a property of the matrix, not columns or rows
* More terminology: full rank, full column-rank, full row-rank, singular
* Rank is the number of dimensions of information
* The rank is the number of columns that form a linearly independent set
* The maximum rank of a matrix is the smaller of mxn

In [2]:
import numpy as np

In [6]:
#FOR COLUMNS

#make a matrix
m = 4
n = 6

#Create a random matrix
A = np.random.randn(m,n)
print(A)

#What is the largest possible rank?
ra = np.linalg.matrix_rank(A)
print(f'Matrix Rank of A is: {str(ra)}')

#set last column to be repeat of penultimate column
B = A
B[:,-1] = B[:,-2]
print(B)

rb = np.linalg.matrix_rank(B)
print(f'rank = {str(rb)}')


[[ 1.877178   -1.64697892 -0.82245847 -0.29305673  0.42799691  0.28490759]
 [-1.41836624 -0.15835601 -1.22249043  0.56654793  0.75376234 -2.41319284]
 [ 0.08400314 -1.34248617 -0.12332643 -0.4528198  -1.03288494  0.64202689]
 [-0.48122275 -0.74403001  2.25786511  0.22507214  0.31071664 -0.16448357]]
Matrix Rank of A is: 4
[[ 1.877178   -1.64697892 -0.82245847 -0.29305673  0.42799691  0.42799691]
 [-1.41836624 -0.15835601 -1.22249043  0.56654793  0.75376234  0.75376234]
 [ 0.08400314 -1.34248617 -0.12332643 -0.4528198  -1.03288494 -1.03288494]
 [-0.48122275 -0.74403001  2.25786511  0.22507214  0.31071664  0.31071664]]
rank = 4


In [7]:
#FOR ROWS

#make a matrix
m = 4
n = 6

#Create a random matrix
A = np.random.randn(m,n)
print(A)

#What is the largest possible rank?
ra = np.linalg.matrix_rank(A)
print(f'Matrix Rank of A is: {str(ra)}')

#set last column to be repeat of penultimate row
B = A
B[-1,:] = B[-2,:]
print(B)

rb = np.linalg.matrix_rank(B)
print(f'rank = {str(rb)}')

[[-1.09435244 -0.74146349  0.29305621  0.10371933  0.36358061 -0.37818367]
 [ 0.64190922 -2.72445135  0.58519713 -0.07956601 -0.5116523  -0.41316593]
 [-0.79643817 -0.30572857  0.69658339  2.63265184 -0.00638201  0.7141664 ]
 [ 0.60460535 -2.26984297  0.36664555  0.30937949 -1.28219384 -0.65338515]]
Matrix Rank of A is: 4
[[-1.09435244 -0.74146349  0.29305621  0.10371933  0.36358061 -0.37818367]
 [ 0.64190922 -2.72445135  0.58519713 -0.07956601 -0.5116523  -0.41316593]
 [-0.79643817 -0.30572857  0.69658339  2.63265184 -0.00638201  0.7141664 ]
 [-0.79643817 -0.30572857  0.69658339  2.63265184 -0.00638201  0.7141664 ]]
rank = 3


In [14]:
#adding noise to a rank-deficient matrix

#square for convenience
A = np.round(10*np.random.randn(m,m))
print(f'A :\n {A}')

#reduce the rank
A[:,-1] = A[:,-2]
print(f'A with the last 2 columns equal:\n {A}')

#noise level
noiseamp = 0.01

#add the noise
B = A + noiseamp*np.random.randn(m,m)

print(f'Rank with no noise: \n{str(np.linalg.matrix_rank(A))}')
print(f'Rank with noise: \n{str(np.linalg.matrix_rank(B))}')

A :
 [[  7.   0. -12.  16.]
 [ -1.   5. -20.   0.]
 [  9.  -1.   4.  12.]
 [-17.  -1.  -2.  -8.]]
A with the last 2 columns equal:
 [[  7.   0. -12. -12.]
 [ -1.   5. -20. -20.]
 [  9.  -1.   4.   4.]
 [-17.  -1.  -2.  -2.]]
Rank with no noise: 
3
Rank with noise: 
4


$$ rank(A+B) \leq rank(A) + rank(B) $$
$$\text{rank}(A+B) \leq \min\{\text{rank}(A), \text{rank}(B)\}$$


Consider the following matrices, all 10x10, and their ranks:

A: r=3;  B: r=2;  C: r=1;  D: r=6

If these matrices contained randomly generated numbers, what is the maximum possible rank of the matrix product (A+B)(C+D)?
The maximum possible rank of (C+D) is 7. The maximum possible rank of (A+B) is 5. And the maximum possible rank of multiplied matrices is the smaller of their two ranks, which is 5. We assume that matrices of randomly generated numbers have maximum possible rank